source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target 'ZFRewardVideoDemo' do

    pod 'VungleSDK-iOS', '~> 4.0.9'
    pod 'Masonry'
    pod 'Toast'
    pod 'AdColony', '~> 3.0.6'

end
